#!/usr/bin/env python3
"""Generates shared/fonts/metrics.json from the bundled font files (stdlib only).

FORMAT.md §7.3 says line metrics come from each file's own `head` + `hhea` tables, never
from the platform (CoreText / Skia pick hhea, OS/2 typo or OS/2 win differently). Apps
load metrics.json instead of parsing font binaries. Re-run whenever shared/fonts changes:

    python3 shared/tools/font_metrics.py          # write metrics.json
    python3 shared/tools/font_metrics.py --report # also list fonts where platforms may disagree
"""
import json
import os
import struct
import sys

FONTS = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "fonts"))


def tables(data):
    tag = data[:4]
    if tag not in (b"\x00\x01\x00\x00", b"OTTO", b"true"):
        raise ValueError("not a single-font sfnt (%r)" % tag)
    n = struct.unpack(">H", data[4:6])[0]
    out = {}
    for i in range(n):
        t, _, off, ln = struct.unpack(">4sIII", data[12 + 16 * i: 28 + 16 * i])
        out[t.decode("latin-1")] = data[off: off + ln]
    return out


def metrics(path):
    t = tables(open(path, "rb").read())
    upm = struct.unpack(">H", t["head"][18:20])[0]
    asc, desc, gap = struct.unpack(">hhh", t["hhea"][4:10])
    m = {"unitsPerEm": upm, "ascender": asc, "descender": desc, "lineGap": gap, "wght": None}
    if "fvar" in t:
        fv = t["fvar"]
        axes_off, _, axis_count, axis_size = struct.unpack(">HHHH", fv[4:12])
        for i in range(axis_count):
            a = fv[axes_off + i * axis_size: axes_off + (i + 1) * axis_size]
            tag = a[:4].decode("latin-1")
            mn, df, mx = (v / 65536.0 for v in struct.unpack(">iii", a[4:16]))
            if tag == "wght":
                m["wght"] = [mn, df, mx]
    os2 = t.get("OS/2")
    info = None
    if os2 and len(os2) >= 78:
        fs_sel = struct.unpack(">H", os2[62:64])[0]
        ta, td, tg = struct.unpack(">hhh", os2[68:74])
        wa, wd = struct.unpack(">HH", os2[74:78])
        info = {"useTypo": bool(fs_sel & 0x80), "typo": (ta, td, tg), "win": (wa, wd)}
    return m, info


def main():
    cat = json.load(open(os.path.join(FONTS, "fonts.json"), encoding="utf-8"))
    files, report = {}, []
    for f in cat["fonts"]:
        for x in f["files"]:
            p = x["path"]
            if p in files:
                continue
            m, info = metrics(os.path.join(FONTS, p))
            files[p] = m
            if info:
                hh = (m["ascender"], m["descender"])
                typo = info["typo"][:2]
                win = (info["win"][0], -info["win"][1])
                if hh != typo or hh != win or m["lineGap"] or info["useTypo"]:
                    report.append("%-45s upm %4d hhea %s gap %d | typo %s useTypo %s | win %s"
                                  % (p, m["unitsPerEm"], hh, m["lineGap"], typo, info["useTypo"], win))
    out = {"formatVersion": 1,
           "note": "Generated by shared/tools/font_metrics.py from head/hhea/fvar. FORMAT.md §7.3. Do not edit.",
           "files": dict(sorted(files.items()))}
    with open(os.path.join(FONTS, "metrics.json"), "w", encoding="utf-8") as fh:
        json.dump(out, fh, indent=1)
        fh.write("\n")
    print("metrics.json: %d files" % len(files))
    if "--report" in sys.argv:
        print("%d files where hhea != OS/2 typo/win, lineGap != 0 or USE_TYPO_METRICS is set:" % len(report))
        for r in report:
            print("  " + r)


if __name__ == "__main__":
    main()
